apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
# Fixe SEMPRE uma versão (tag ou digest) em produção; "latest" não é reproduzível.
images:
  - { name: ghcr.io/brunacoelhob/app-loja-veloz/api-gateway, newTag: latest }
  - { name: ghcr.io/brunacoelhob/app-loja-veloz/pedidos, newTag: latest }
  - { name: ghcr.io/brunacoelhob/app-loja-veloz/estoque, newTag: latest }
  - { name: ghcr.io/brunacoelhob/app-loja-veloz/pagamentos, newTag: latest }
