{
 "title": "Loja Veloz: visão geral",
 "tags": [ "loja-veloz" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Serviços no ar",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(up{job=\"loja-veloz\"})"
    }
   ]
  },
  {
   "title": "Requisições por segundo (por serviço)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (servico) (rate(http_request_duration_seconds_count[1m]))",
     "legendFormat": "{{servico}}"
    }
   ]
  },
  {
   "title": "Taxa de erros 5xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (servico) (rate(http_request_duration_seconds_count{status=~\"5..\"}[5m])) / sum by (servico) (rate(http_request_duration_seconds_count[5m]))",
     "legendFormat": "{{servico}}"
    }
   ]
  },
  {
   "title": "Latência p95 (segundos)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, servico) (rate(http_request_duration_seconds_bucket[5m])))",
     "legendFormat": "{{servico}}"
    }
   ]
  },
  {
   "title": "Memória (processo Node.js)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"loja-veloz\"}",
     "legendFormat": "{{servico}}"
    }
   ]
  }
 ]
}